name: InvisAttackEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - anytree==2.13.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - bert-score==0.3.13
      - bioc==2.1
      - boto3==1.42.16
      - botocore==1.42.16
      - bs4==0.0.2
      - click==8.3.1
      - conllu==4.5.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.2
      - deprecated==1.3.1
      - dill==0.4.0
      - docopt==0.6.2
      - editdistance==0.8.1
      - filelock==3.20.0
      - flair==0.15.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gast==0.7.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - intervaltree==3.2.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - keras==3.12.0
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - language-tool-python==3.2.0
      - lemminflect==0.2.3
      - libclang==18.1.1
      - lru-dict==1.4.1
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - more-itertools==10.8.0
      - mpld3==0.5.12
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - namex==0.1.0
      - networkx==3.4.2
      - nltk==3.9.2
      - num2words==0.5.14
      - nvidia-cublas==13.0.0.19
      - nvidia-cuda-cupti==13.0.48
      - nvidia-cuda-nvrtc==13.0.48
      - nvidia-cuda-runtime==13.0.48
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.15
      - nvidia-cufile==1.15.0.42
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.3.29
      - nvidia-cusparse==12.6.2.49
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.39
      - nvidia-nvshmem-cu13==3.3.24
      - nvidia-nvtx==13.0.39
      - openhownet==2.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pinyin==0.4.0
      - pptree==3.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pyparsing==3.3.1
      - pysocks==1.7.1
      - pytorch-revgrad==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rich==14.2.0
      - s3transfer==0.16.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segtok==1.5.11
      - sentencepiece==0.2.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8.1
      - sqlitedict==2.1.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-hub==0.16.1
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - textattack==0.3.10
      - tf-keras==2.20.1
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - transformer-smaller-training-vocab==0.4.2
      - triton==3.5.1
      - tzdata==2025.3
      - wikipedia-api==0.8.1
      - word2number==1.1
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /local/scratch/stk31/miniconda3/envs/InvisAttackEnv
